### ISSUE TITLE
Component does not work in Delphi 11.2 Patch 1

### ISSUE THREAD

**Issue by jfanton2964** [adrianosantostreina/MobilePermissions#34]
This only shows Win32 as only supported platform on component toolbar.  Compiling does not work for Android target builds.  Strange that an Android specific component is only supported for the Win32 platform.  It worked on the trial version of Delphi 11 but not on the registered version 11.2.

**Comment by cleberDeveloper** [comment]
Bom dia, comigo acontece a mesma coisa.
![Sem título](https://user-images.githubusercontent.com/121617483/209954667-3aca7221-9282-475a-ace0-c0cfc2f742be.png)

**Comment by jcanepa12** [comment]
Having the same issue here.  Running Delphi 11.2 (Embarcadero® RAD Studio 11 Version 28.0.46141.0937)
It compiles and installs fine but when I compile a project I get the same errors.
[DCC Error] MobilePermissions.JNI.Os.Base.pas(173): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(178): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(183): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(188): E2010 Incompatible types: 'JString' and 'string'
...

**Comment by dpcroghan** [comment]
I am also on Embarcadero® RAD Studio 11 Version 28.0.46141.0937 and am unable to compile for Android.  
I receive same errors as jcanepa12.
[DCC Error] MobilePermissions.JNI.Os.Base.pas(173): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(178): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(183): E2010 Incompatible types: 'JString' and 'string'
[DCC Error] MobilePermissions.JNI.Os.Base.pas(188): E2010 Incompatible types: 'JString' and 'string'

**Comment by dpcroghan** [comment]
I also receive the following error messages when attempting to compile:
[DCC Error] MobilePermissions.UsesPermissions.FMX.Standard.pas(163): E2003 Undeclared identifier: 'CALL_COMPANION_APP'
[DCC Error] MobilePermissions.UsesPermissions.FMX.Standard.pas(418): E2003 Undeclared identifier: 'CALL_COMPANION_APP'

**Comment by adrianosantostreina** [comment]
We were unable to complete updates to the component. However, it is on our roadmap to make the necessary changes, as well as add new properties.

The component is OpenSource, that means the community can contribute. Any developer who wants to make corrections, just make a Fork of the project, correct and send the PullRequest that we will analyze and accept if everything is ok.

There is interest in making this contribution to us

**Comment by adrianosantostreina** [comment]
Finally we managed to tweak everything needed in the component to be compatible with Delphi 11.x

We are preparing a new version with other new properties.

Do your tests and let us know.
Thanks

**Comment by dpcroghan** [comment]
Thank you!DanOn Mar 2, 2023, at 12:19 PM, Adriano Santos Treinamentos ***@***.***> wrote:﻿
Closed #34 as completed.
